### ISSUE TITLE
GDPR compliance: single private IPFS cluster across environment

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/infrastructure#111]
## Description
As a host, I want to be gdpr compliant in my storage of avatars.

## Acceptance criteria

- [ ] Restrict ipfs server to be a single server domain i.e. a private cluster

Note: Rene has researched what needs to be done, need to see how to automate / do manually for each environment.

**Comment by valentinyanakiev** [comment]
The following actions need to be performed to create a private IPFS cluster (uh, node ;)):

remove the bootstrap entry in the config file: ipfs bootstrap rm --all
create a swarm key: echo -e "/key/swarm/psk/1.0.0/\n/base16/\ntr -dc 'a-f0-9' < /dev/urandom | head -c64" > ~/.ipfs/swarm.key
force the use of a private cluster: export LIBP2P_FORCE_PNET=1
set the swarm key file: export IPFS_SWARM_KEY_FILE=/path/to/swarm.key
start daemon
