### ISSUE TITLE
BUG: Kratos emails are not received on ACC

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/infrastructure#120]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/identity/registration
2. Fill up the detail of a user and use email, to which you have access to the email client
3. Press sign up button - email is not received in the email client

### Note:
Email containing verification link is generated in KratosDB

**Expected behavior**
Users receive all Kratos emails

**Comment by valentinyanakiev** [comment]
next time just delete the container of kratos and kratos courier
that fixes it
