### ISSUE TITLE
Spike: Evaluate notification services for out of band communications

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/infrastructure#90]
## Description
As an ecoverse host I want to be able to proactively communicate with the community out of band

## Acceptance criteria

- [x] Investigate + detail out options for notification services that support at least the following channels: email
- [x] Timebox to a day
- [x] Emails to be based on hard coded templates

**Comment by valentinyanakiev** [comment]
It seems like [notif.me](https://github.com/notifme) is a comprehensive, open-source, MIT-licensed library that can support different notification channels, such as email, SMS, push notifications (apple, kindle, android), SMTP (plenty of providers out-of-the-box, including AWS SES, that we use).

It supports the following:
- different 'channels' to output to, very well abstracted as well - SMS, email, push etc.
- [native rabbitmq queue support](https://github.com/notifme/notifme-sdk-queue-rabbitmq)
- multiple provider strategies
- [templating](https://github.com/notifme/notifme-template) - supports email templates

The library / set of libraries has extensive documentation as well.
